services:
  kafka:
    image: apache/kafka:4.1.2
    container_name: practice-kafka
    ports:
      - "9092:9092"

  redis:
    image: redis:7
    container_name: practice-redis
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus:latest
    container_name: practice-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: practice-grafana
    ports:
      - "3000:3000"